STYLE: Remove virtual from itkGPUKernelClassMacro, use C++11 `= delete`
InsightSoftwareConsortium/ITK pull request #2332
Opened 2021-02-23 10:57 UTC by N-Dekker

Deleted all special member functions of GPU kernel helper classes
defined by `itkGPUKernelClassMacro(kernel)`, by C++11 `= delete`.

Note that construction, destruction, copy, and move were previously
already disabled by declaring their special member functions `private`.
So this adjustment is just a style modernization, not an API change.

Made the destructor non-virtual, to avoid the definition of a virtual
table for these classes.

2021-02-23 12:51 UTC, phcerdan requested changes

2021-02-23 12:51 UTC, phcerdan commented on Modules/Core/Common/include/itkMacro.h
> +    ~kernel() = delete;                                                                                                \
delete on a non-virtual destructor? My alarms just switched on, can you expand on this? Where have you seen this pattern? Did you mean default?

2021-02-23 12:53 UTC, phcerdan commented on Modules/Core/Common/include/itkMacro.h
> +    ~kernel() = delete;                                                                                                \
if this class cannot be constructed, and not deleted, is there any better way to represent it?

2021-02-23 13:19 UTC, phcerdan reviewed
-

2021-02-23 13:23 UTC, phcerdan approved these changes

2021-02-23 13:25 UTC, phcerdan commented on Modules/Core/Common/include/itkMacro.h
> +    ~kernel() = delete;                                                                                                \
Ok, I see this limits the usage to only the static function.

2021-02-23 16:50 UTC, thewtex approved these changes
Nice, thank you @N-Dekker !

2021-02-24 20:30 UTC, dzenanz approved these changes

2021-02-24 20:30 UTC, merged