BUG: check if vtrype is not INVALID
InsightSoftwareConsortium/ITK pull request #2553
Opened 2021-05-26 18:30 UTC by mrc-sys

BUG: Only access the value of si , if vrtype is not invalid. This prevents a SegmentationFault in the case of an invalid tag

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

2021-05-26 18:44 UTC, dzenanz reviewed
LGTM

2021-05-26 22:24 UTC, jhlegarreta commented
@mrc-sys Thanks for contributing to ITK :100: !

Can you please remove commit 4ed3b6fd187a733761217a4cbb52e9b81972f55d in the branch, as it is a duplicate of the latter b300ae27ad7e11e8b65c924fe1a6e5cd6d504046, this one having the [appropriate style for an ITK commit](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#commit-messages)? Thanks !

2021-05-27 05:53 UTC, malaterre requested changes
You're avoiding a segfault by hiding the symptoms. I suspect this creates an empty Data Element, this is not a desired behavior AFAIK.

2021-06-08 09:58 UTC, mrc-sys commented
> @mrc-sys Thanks for contributing to ITK 100 !
> 
> Can you please remove commit [4ed3b6f](https://github.com/InsightSoftwareConsortium/ITK/commit/4ed3b6fd187a733761217a4cbb52e9b81972f55d) in the branch, as it is a duplicate of the latter [b300ae2](https://github.com/InsightSoftwareConsortium/ITK/commit/b300ae27ad7e11e8b65c924fe1a6e5cd6d504046), this one having the [appropriate style for an ITK commit](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#commit-messages)? Thanks !

Can you describe me, how to remove the commit? I am happy to get the later commit in the appropriate style....

2021-06-08 10:06 UTC, mrc-sys commented
> You're avoiding a segfault by hiding the symptoms. I suspect this creates an empty Data Element, this is not a desired behavior AFAIK.
If it´s possible to avoid the crash in a better way, I would prefer the better solution. But for now I have not found this better solution and this segfault is a showstopper for me.

2021-06-08 12:36 UTC, jhlegarreta commented
> Can you describe me, how to remove the commit? I am happy to get the later commit in the appropriate style....

You should rebase interactively using `git rebase -i HEAD~2` then mark the commit to be deleted with `d` (for drop), exit with `:wq`, then continue the rebase with `git rebase --continue`, and it should be fine. Then you would `git push -f origin {your_branch_name}` to push to the repository.

2021-06-08 13:35 UTC, mrc-sys commented
> > Can you describe me, how to remove the commit? I am happy to get the later commit in the appropriate style....
> 
> You should rebase interactively using `git rebase -i HEAD~2` then mark the commit to be deleted with `d` (for drop), exit with `:wq`, then continue the rebase with `git rebase --continue`, and it should be fine. Then you would `git push -f origin {your_branch_name}` to push to the repository.

Can this be done in the github web-gui too?

2021-06-08 13:53 UTC, malaterre commented
@mrc-sys 

> If it´s possible to avoid the crash in a better way, I would prefer the better solution. But for now I have not found this better solution and this segfault is a showstopper for me.

You'll need to provide us more detail on how to reproduce the segfault. Or simply dump part of the backtrace (eg. 'bt' under gdb).

2021-06-08 14:41 UTC, dzenanz commented
I don't think rebase can be done in GitHub WebUI. But it can be done in e.g. TortoiseGit and `gitk`.

2021-06-08 15:41 UTC, mrc-sys commented
> @mrc-sys
> 
> > If it´s possible to avoid the crash in a better way, I would prefer the better solution. But for now I have not found this better solution and this segfault is a showstopper for me.
> 
> You'll need to provide us more detail on how to reproduce the segfault. Or simply dump part of the backtrace (eg. 'bt' under gdb).

I will try to reproduce the error again, but I have patched ITK 4.13.1 about 4 years ago (ubuntu 16.04) and the bug popped up again on porting our application to ubuntu 20.04 and ITK 4.13.3. As the patch solved the problem again and the source was not changed in the meantime, I have not tested without the patch again.

2021-10-04 01:15 UTC, thewtex commented
Addressing style issues

2026-05-01 22:43 UTC, hjmjohnson commented
Reviving this for resolution. I've opened **#6185** which carries the same fix forward, addresses @malaterre's CHANGES_REQUESTED concern from this thread, and adds regression-test coverage (a Google Test that demonstrates the crash on `main` and confirms the fix). Original authorship is preserved via `Co-Authored-By: mrc-sys` trailers on both commits.

<details>
<summary>What changed vs. this PR</summary>

The fix in #6185 lifts the `gdcm::VR::INVALID` check **above** the per-VR dispatch and routes the unknown tag through the existing `problematicKeys` channel — so no empty `gdcm::DataElement` is ever constructed for an unknown tag. That directly addresses @malaterre's *"You're avoiding a segfault by hiding the symptoms. I suspect this creates an empty Data Element"* concern from this PR. The user gets a single `itkWarning` listing all unknown keys at the end of the dictionary iteration (same UX the function already produces for non-DICOM keys) instead of a process abort.

Two regression `TEST()` cases verify the path locally:
1. Pre-fix: writer dies with `gdcm::Exception "An invalid logic behavior occurred"` (gdcmVR.cxx:263).
2. Post-fix: writer completes, expected warning emitted, output file has all valid metadata.

</details>

@mrc-sys — thanks for spotting and reporting this in 2021. If #6185 looks reasonable to you and the maintainers, this PR can be closed as superseded.

2026-05-01 22:44 UTC, closed without merging