STYLE: ITK_FUTURE_LEGACY_REMOVE itkStaticConstMacro
InsightSoftwareConsortium/ITK pull request #2868
Opened 2021-11-11 22:03 UTC by hjmjohnson

itkStaticConstMacro(name, type, value) is now unconditional in its
behavior.

Use C++11 language syntax directly.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

2021-11-11 23:09 UTC, dzenanz approved these changes

2021-11-11 23:09 UTC, dzenanz commented
Linter is unhappy.

2021-11-11 23:23 UTC, dzenanz approved these changes

2021-11-12 09:39 UTC, N-Dekker requested changes
This pull request appears redundant. Please check:

https://github.com/InsightSoftwareConsortium/ITK/blob/67b3b19d178a6f2c124847ce22b824930eb1a24d/Modules/Core/Common/include/itkMacro.h#L788-L790

2021-11-12 09:43 UTC, N-Dekker commented
Looks like a duplicate of pull request #2767 "STYLE: Remove itkstatic const macro future deprecate"! Please do not merge!

2021-11-12 13:27 UTC, hjmjohnson commented
Thanks for catching this @N-Dekker .

2021-11-12 13:27 UTC, closed without merging