ENH: Raw Pointer for Python Wrapping
InsightSoftwareConsortium/ITK pull request #2910
Opened 2021-11-30 23:20 UTC by PranjalSahu

Minor changes for better code readability and for optimized Python wrapping.
Using Raw Pointer instead of Smart Pointer.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [X] Updated API documentation (or API not changed)
- [X] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [X] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [X] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

2021-11-30 23:23 UTC, PranjalSahu commented
@thewtex I didn't do the change to convert K and dA variables to Double vector container as in the loop we are accessing values at various indexes  in non-serial order and using GetElement/SetElement is going to be inefficient in such case (function call stack). Please let me know if there is better alternative.

2021-12-01 22:50 UTC, PranjalSahu commented
Should I create separate commits for these changes ?

2021-12-01 23:10 UTC, dzenanz commented
You can. Maybe into 3? "Use raw pointer", "Add testing", "Fix wrapping", not necessarily in this order.

2021-12-02 21:38 UTC, dzenanz approved these changes

2021-12-02 21:38 UTC, dzenanz commented on Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.h
> +#include "itkTriangleCell.h"
When you have an "**and**" in commit message, it is a good indication it should be split into two commit. There is no limit how small commits can be. I do realize this is nitpicking, so feel free to ignore this time.

2021-12-03 00:11 UTC, thewtex requested changes
@PranjalSahu thanks! Follow-up noted inline.

2021-12-03 00:11 UTC, thewtex commented on Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.h
> -  GetGaussCurvature(MeshConstPointer input);
We want to remove the smart pointer from the interface here.

2021-12-03 00:11 UTC, thewtex commented on Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.h
> -  MeshConstPointer             m_TriangleMesh;
This still needs to be a smart pointer (we want to hold a reference to the object).

2021-12-03 16:13 UTC, dzenanz approved these changes

2021-12-06 16:26 UTC, merged

2021-12-07 13:57 UTC, jhlegarreta commented
@PranjalSahu one of these two commits causes a memory leak 59d95db 4aab01e:
https://open.cdash.org/viewDynamicAnalysis.php?buildid=7611627

2021-12-07 16:40 UTC, PranjalSahu commented
I will check it. It is probably due to the newly added check for Triangle
Cell. I have to see whether the memory allocated for K and dA are properly
released after the itkExceptionMacro is called.

On Tue, Dec 7, 2021 at 8:58 AM Jon Haitz Legarreta Gorroño <
***@***.***> wrote:

> @PranjalSahu <https://github.com/PranjalSahu> one of these two commits
> causes a memory leak 59d95db
> <https://github.com/InsightSoftwareConsortium/ITK/commit/59d95db27307e585d1670ae94ef855f1db468176>
> 4aab01e
> <https://github.com/InsightSoftwareConsortium/ITK/commit/4aab01e8ec468b33c7660031dc1d2244f801dba8>
> :
> https://open.cdash.org/viewDynamicAnalysis.php?buildid=7611627
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/InsightSoftwareConsortium/ITK/pull/2910#issuecomment-987950093>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH65J2V2P43LXNPE6AWDBTUPYHGVANCNFSM5JDBIU6Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-10 20:09 UTC, PranjalSahu commented
I think it is due to the TetrahedronCell inserted in the mesh. 
The documentation for [SetCell](https://itk.org/Doxygen/html/classitk_1_1Mesh.html#af48765961f72f75c8d2c6a1d12cd0124) in itk mesh says:

**Access routines to fill the Cells container (m_CellsContainer), and get information from it. If SetCell is used to overwrite a cell currently in the mesh, it is the caller's responsibility to release the memory for the cell currently at the CellIdentifier position prior to calling SetCell.**

So we need to the release the memory of the original cell present in the mesh before setting the new TetrahedronCell.
Testing it and will update here.