Extend RawImage wrapper to other data types
InsightSoftwareConsortium/ITK pull request #3190
Opened 2022-02-10 22:38 UTC by ferdymercury

Fixes https://github.com/InsightSoftwareConsortium/ITK/issues/3184

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

2022-02-10 22:39 UTC, ferdymercury commented
I copied the same structure than in https://github.com/InsightSoftwareConsortium/ITK/blob/047fa6934ac32711d1d7b84fa6eb81c72db01960/Modules/Filtering/ImageGrid/wrapping/itkResampleImageFilter.wrap#L7

2022-02-10 23:01 UTC, dzenanz requested changes

2022-02-10 23:01 UTC, dzenanz commented on Modules/IO/RAW/wrapping/itkRawImageIO.wrap
> +      itk_wrap_template("${ITKM_VI${t}${d}}${ITKM_VI${t}${d}}" "${ITKT_VI${t}${d}},${ITKT_VI${t}${d}}")
`VI` means VectorImage, and this is a rarely used type.
```suggestion
      itk_wrap_template("${ITKM_${t}${d}}${ITKM_${t}${d}}" "${ITKT_${t}${d}},${ITKT_${t}${d}}")
```

2022-02-10 23:02 UTC, dzenanz commented on Modules/IO/RAW/wrapping/itkRawImageIO.wrap
> +      itk_wrap_template("${ITKM_VI${t}${d}}${ITKM_VI${t}${d}}" "${ITKT_VI${t}${d}},${ITKT_VI${t}${d}}")
Alternatively, use `itk_wrap_image_filter("${WRAP_ITK_SCALAR}" 2)` which will have about the same effect.

2022-02-10 23:07 UTC, dzenanz reviewed
Your commit message needs `ENH: ` prefix.

2022-02-10 23:22 UTC, ferdymercury commented
> Your commit message needs `ENH: ` prefix.

Changed.

2022-02-10 23:30 UTC, dzenanz approved these changes

2022-02-13 22:00 UTC, ferdymercury commented
There seems to be some errors:

```
2022-02-11T02:03:19.4372668Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:26:30: error: expected expression
2022-02-11T02:03:19.4373891Z     typedef itk::RawImageIO< , > itkRawImageIO;
2022-02-11T02:03:19.4374578Z                              ^
2022-02-11T02:03:19.4375718Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:27:30: error: expected expression
2022-02-11T02:03:19.4376797Z     typedef itk::RawImageIO< , >::Pointer itkRawImageIO_Pointer;
2022-02-11T02:03:19.4377483Z                              ^
2022-02-11T02:03:19.4378823Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:29:30: error: expected expression
2022-02-11T02:03:19.4380060Z     typedef itk::RawImageIO< , > itkRawImageIO;
2022-02-11T02:03:19.4380756Z                              ^
2022-02-11T02:03:19.4381752Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:30:30: error: expected expression
2022-02-11T02:03:19.4382647Z     typedef itk::RawImageIO< , >::Pointer itkRawImageIO_Pointer;
2022-02-11T02:03:19.4383601Z                              ^
2022-02-11T02:03:19.4384667Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:32:30: error: expected expression
2022-02-11T02:03:19.4385754Z     typedef itk::RawImageIO< , > itkRawImageIO;
2022-02-11T02:03:19.4386719Z                              ^
2022-02-11T02:03:19.4387745Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:33:30: error: expected expression
2022-02-11T02:03:19.4389324Z     typedef itk::RawImageIO< , >::Pointer itkRawImageIO_Pointer;
2022-02-11T02:03:19.4389896Z                              ^
2022-02-11T02:03:19.4390688Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:35:30: error: expected expression
2022-02-11T02:03:19.4391407Z     typedef itk::RawImageIO< , > itkRawImageIO;
2022-02-11T02:03:19.4391882Z                              ^
2022-02-11T02:03:19.4392642Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:36:30: error: expected expression
2022-02-11T02:03:19.4393502Z     typedef itk::RawImageIO< , >::Pointer itkRawImageIO_Pointer;
2022-02-11T02:03:19.4394029Z                              ^
2022-02-11T02:03:19.4395111Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:38:30: error: expected expression
2022-02-11T02:03:19.4395848Z     typedef itk::RawImageIO< , > itkRawImageIO;
2022-02-11T02:03:19.4396450Z                              ^
2022-02-11T02:03:19.4397219Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:39:30: error: expected expression
2022-02-11T02:03:19.4397928Z     typedef itk::RawImageIO< , >::Pointer itkRawImageIO_Pointer;
2022-02-11T02:03:19.4398443Z                              ^
2022-02-11T02:03:19.4399202Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:41:30: error: expected expression
2022-02-11T02:03:19.4399931Z     typedef itk::RawImageIO< , > itkRawImageIO;
2022-02-11T02:03:19.4400405Z                              ^
2022-02-11T02:03:19.4401163Z /home/vsts/work/1/s-build/Wrapping/itkRawImageIO.cxx:42:30: error: expected expression
2022-02-11T02:03:19.4401887Z     typedef itk::RawImageIO< , >::Pointer itkRawImageIO_Pointer;
2022-02-11T02:03:19.4402390Z                              ^
2022-02-11T02:03:19.4402803Z 12 errors generated.
```

2022-02-14 15:50 UTC, dzenanz commented on Modules/IO/RAW/wrapping/itkRawImageIO.wrap
>    endforeach()
```suggestion
  itk_wrap_image_filter("${to_types}" 2)
```

2022-02-14 15:50 UTC, dzenanz commented on Modules/IO/RAW/wrapping/itkRawImageIO.wrap
>    endforeach()
There seems to be something wrong with C++ template type specification. Let's try this shorter form.

2022-02-14 16:14 UTC, dzenanz approved these changes

2022-02-15 16:17 UTC, thewtex requested changes
@ferdymercury thanks for the contribution.

Please try the approach suggested inline.

The wrapping macros are explained in the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf). These should be used considering the declaration of RawImageIO:

`to_types` -> `types`

2022-02-15 16:22 UTC, ferdymercury commented on Modules/IO/RAW/wrapping/itkRawImageIO.wrap
> +  itk_wrap_image_filter("${to_types}" 2)
thanks for the hint

2022-02-17 17:34 UTC, thewtex approved these changes
Thanks @ferdymercury

2022-02-17 17:34 UTC, merged