COMP: Bump CastXML amd64 binaries to 0.4.5 for Windows 11 support
InsightSoftwareConsortium/ITK pull request #3324
Opened 2022-03-22 16:48 UTC by thewtex

2022-03-22 16:51 UTC, thewtex commented
Closes #3216

2022-03-22 16:53 UTC, bradking approved these changes

2022-03-22 17:09 UTC, dzenanz approved these changes

2022-03-23 14:48 UTC, thewtex commented
\azp run ITK.macOS.Python

2022-03-23 15:02 UTC, thewtex commented
/azp run ITK.macOS.Python

2022-04-02 15:14 UTC, aylward commented
Looks like the Mac version of castxml has a packaging error:
https://dev.azure.com/itkrobotmacospython/ITK.macOS.Python/_build/results?buildId=6827&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5add3200-7efa-59c0-0a45-43bce0c77c69&l=5424

2022-04-02 17:01 UTC, aylward commented
Did not work on Windows 11.

> ninja

FAILED: Wrapping/itkVariableSizeMatrix.xml
cmd.exe /C "cd /D C:\src\ITK-Release\Wrapping\Modules\ITKCommon && C:\src\ITK-Release\Wrapping\Generators\CastXML\castxml\bin\castxml.exe -o C:/src/ITK-Release/Wrapping/itkVariableSizeMatrix.xml --castxml-gccxml --castxml-start _wrapping_ --castxml-cc-msvc ( "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" /DWIN32 /D_WINDOWS /GR /EHsc -W3 /bigobj /bigobj -std:c++14 ) -fexceptions -w -c @C:/src/ITK-Release/Wrapping/ITKCommon.castxml.inc C:/src/ITK-Release/Wrapping/itkVariableSizeMatrix.cxx"
'C:\src\ITK-Release\Wrapping\Generators\CastXML\castxml\bin\castxml.exe' is not recognized as an internal or external command, operable program or batch file.

> ls /c/src/ITK-Release/Wrapping/Generators/CastXML/castxml/bin

castxml

> cd /c/src/ITK-Release/Wrapping/Generators/CastXML/castxml/bin
> mv castxml castxml.exe
> cd /c/src/ITK-Release
> ninja

FAILED: Wrapping/ITKCommonBase.xml
cmd.exe /C "cd /D C:\src\ITK-Release\Wrapping\Modules\ITKCommon && C:\src\ITK-Release\Wrapping\Generators\CastXML\castxml\bin\castxml.exe -o C:/src/ITK-Release/Wrapping/ITKCommonBase.xml --castxml-gccxml --castxml-start _wrapping_ --castxml-cc-msvc ( "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" /DWIN32 /D_WINDOWS /GR /EHsc -W3 /bigobj /bigobj -std:c++14 ) -fexceptions -w -c @C:/src/ITK-Release/Wrapping/ITKCommon.castxml.inc C:/src/ITK-Release/Wrapping/ITKCommonBase.cxx"
This version of C:\src\ITK-Release\Wrapping\Generators\CastXML\castxml\bin\castxml.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

2022-04-02 17:14 UTC, aylward requested changes
Hash tags got swapped.   Not certain what is the right version for Darwin x86_64 - didn't see it on data.kitware.com

2022-04-02 17:14 UTC, aylward commented on Wrapping/Generators/CastXML/CMakeLists.txt
> +    set(_castxml_hash 56cf92eb9ca543a6178689643d32a455da1f92da78ca58a8cb671798ac9f903dc6b687be1d3824ab0211ed49724b62185a21874810139de7dbb6cb39f63b860f)
This is the hash for the windows version, not the mac version.

https://data.kitware.com/#item/622961504acac99f42134aab

2022-04-02 17:14 UTC, aylward commented on Wrapping/Generators/CastXML/CMakeLists.txt
> +    set(_castxml_hash 5faef93541cb5f30414286a844e47b5732777f26246c6e0933170668e9cf2ff4f3fa4292e861e73e91ed50971caa9d6e7481eead9c9cefda6d54a9042634bf5c)
The proper hash is 
56cf92eb9ca543a6178689643d32a455da1f92da78ca58a8cb671798ac9f903dc6b687be1d3824ab0211ed49724b62185a21874810139de7dbb6cb39f63b860f
See
https://data.kitware.com/#item/622961504acac99f42134aab

2022-04-02 17:53 UTC, aylward commented on Wrapping/Generators/CastXML/CMakeLists.txt
> +    set(_castxml_hash 5faef93541cb5f30414286a844e47b5732777f26246c6e0933170668e9cf2ff4f3fa4292e861e73e91ed50971caa9d6e7481eead9c9cefda6d54a9042634bf5c)
When I update to the proper hash, all works!!!

2022-04-18 19:29 UTC, thewtex commented
Superceded by #3385

2022-04-18 19:29 UTC, closed without merging