BUG: Fix Doxygen configuration for output formats
InsightSoftwareConsortium/ITK pull request #3346
Opened 2022-03-30 12:59 UTC by blowekamp

Convert CMake bool to YES/NO, and correct name for configuration
variables.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

2022-03-30 13:13 UTC, dzenanz approved these changes

2022-03-30 13:27 UTC, hjmjohnson requested changes
I thought the CMake macro did this.  Perhaps an update to the cmake doxygen wrapper is needed to make it better.

I am sorry for removing this logic during the refactoring.  The similar code needs to be added to 

./Wrapping/DoxygenConfig.cmake

2022-03-30 15:46 UTC, hjmjohnson commented
> > I thought the CMake macro did this. Perhaps an update to the cmake doxygen wrapper is needed to make it better.
> > I am sorry for removing this logic during the refactoring. The similar code needs to be added to ./Wrapping/DoxygenConfig.cmake
> 
> Does the wrapping need every thing or just the XML?

I'm hoping to find a way to merge both of these files eventually.  I think wrapping just needs the XML, but having the exac same code should not hurt.

2022-03-31 14:12 UTC, hjmjohnson approved these changes
I am approving this good step forward.  I'll address the doxygen for wrapping in the near future as a separate PR.

2022-03-31 14:12 UTC, merged