DRAFT: Removing TransformType key from Transform serialization
InsightSoftwareConsortium/ITK pull request #3470
Opened 2022-06-20 07:11 UTC by PranjalSahu

- Removed TransformType key from Transform dict.
- Added test for BSpline Transform for testing transformation output before and after serialization.
- Removed the first Composite transform from the dict array. However, there is one issue with this approach. The dictionary is a list of transforms present inside the composite transform and the name for composite transform cannot be transferred here.  We need to decide if that will be needed. 

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

2022-06-27 21:10 UTC, PranjalSahu commented
@thewtex Do we want to give the functionality to change the **inputSpace** and **outputSpace** fields ?
For this, we will have to add string entries in the [itk::Transform](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Transform/include/itkTransform.hxx) class definition and not just in the dict_from_transform.

2022-06-28 12:28 UTC, thewtex commented
> add string entries in the itk::Transform class definition and not just in the dict_from_transform.

@PranjalSahu yes, please

2022-06-29 13:38 UTC, jhlegarreta submitted a review, later dismissed

2022-06-29 13:38 UTC, jhlegarreta commented on Modules/Core/Transform/include/itkTransform.h
> +  itkGetConstReferenceMacro(OutputSpaceName, std::string);
Please exercise the added methods in the corresponding C++ test.

2022-06-29 19:07 UTC, thewtex reviewed
@PranjalSahu awesome, thank you! I like each transform name having the `name`, `inputSpace`, `outputSpace`.  We have the composite transform `inputSpace`, `outputSpace` by looking at `composite[0]['inputSpace']`, `composite[-1]['outputSpace']` -- best not to duplicate that information.

One minor change as suggested by @jhlegarreta 

```
 std::cout << transform->GetInputSpaceName() << std::endl;
```

->

```
ITK_TEST_EXPECT_EQUAL(std::string("test_inputspace"), transform->GetInputSpaceName());
```

2022-06-29 22:34 UTC, jhlegarreta commented on Modules/Core/Transform/include/itkTransform.h
> +  itkGetConstReferenceMacro(OutputSpaceName, std::string);
Done in 5da379a. Thanks @PranjalSahu and @thewtex for the comment to ensure that the calls return what is expected.

2022-06-29 22:39 UTC, jhlegarreta reviewed
Looks good to me, but I am deferring to @thewtex the approval.

BTW @PranjalSahu only one of the commit messages has a body, and the imperative mood should be used in the subject line. See [CONTRIBUTING.md#commit-messages](https://github.com/InsightSoftwareConsortium/ITK/blob/23da3dfa79152648f3d38050ee147df47f41ce0a/CONTRIBUTING.md#commit-messages).

2022-06-29 23:43 UTC, PranjalSahu commented
> Looks good to me, but I am deferring to @thewtex the approval.
> 
> BTW @PranjalSahu only one of the commit messages has a body, and the imperative mood should be used in the subject line of any commit. See [CONTRIBUTING.md#commit-messages](https://github.com/InsightSoftwareConsortium/ITK/blob/23da3dfa79152648f3d38050ee147df47f41ce0a/CONTRIBUTING.md#commit-messages).

I have added more messages and changed the commit subject.

2022-06-29 23:52 UTC, PranjalSahu commented
I am doing some additional testing locally with the ICON registration transform.

2022-06-30 01:06 UTC, jhlegarreta commented
> I have added more messages and changed the commit subject.

:100: Thanks.

2022-06-30 03:44 UTC, thewtex approved these changes

2022-06-30 16:58 UTC, PranjalSahu commented
Please wait for my confirmation before merging.

2022-06-30 17:52 UTC, PranjalSahu commented
Ok, it can be merged 👍.
Tested the output with ICON registration model also.

2022-06-30 18:35 UTC, thewtex requested changes
@PranjalSahu awesome!

One minor change noted inline per discussion.

2022-06-30 18:35 UTC, thewtex commented
CC @HastingsGreer

2022-07-01 14:28 UTC, thewtex approved these changes

2022-07-01 14:29 UTC, thewtex commented
:100: :1st_place_medal:

2022-07-01 14:29 UTC, merged