WIP: Add DistanceThreshold parameter in EuclideanDistance Metricv4
InsightSoftwareConsortium/ITK pull request #3728
Opened 2022-11-08 16:02 UTC by PranjalSahu

Points beyond the DistanceThreshold parameter are skipped in the derivative and value calculation.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

2022-11-08 16:40 UTC, dzenanz approved these changes

2022-11-11 14:24 UTC, jhlegarreta requested changes

2022-11-11 14:24 UTC, jhlegarreta commented on Modules/Registration/Metricsv4/test/itkEuclideanDistancePointSetMetricTest3.cxx
> +  metric->SetDistanceThreshold(distanceThreshold);
Please exercise the `GetDistanceThreshold` method here using the `ITK_TEST_SET_GET_VALUE` macro.

2022-11-11 14:24 UTC, jhlegarreta commented on Modules/Registration/Metricsv4/test/itkEuclideanDistancePointSetMetricTest3.cxx
> +  double distanceThreshold = 0.5;
Are all the added `if/else` cases concerning the distance threshold value exercised in this test? Maybe the ones not covered here are covered in other tests through the default value. But for the sake of completeness, I would make sure all are tested here, maybe by making the value of the threshold (and the expected output values, if necessary) be a parameter of the method.

2022-11-11 19:55 UTC, jhlegarreta commented on Modules/Registration/Metricsv4/test/itkEuclideanDistancePointSetMetricTest3.cxx
> +  double distanceThreshold = 0.5;
:100: Thanks @PranjalSahu.

2022-11-11 20:02 UTC, jhlegarreta reviewed
Some comments to improve the style of the test.

2022-11-11 20:02 UTC, jhlegarreta commented on Modules/Registration/Metricsv4/test/itkEuclideanDistancePointSetMetricTest3.cxx
> +    std::cerr << "Failed for Dimension 2." << std::endl;
The message could be more specific; now they do not allow knowing which case caused an error
```
constexpr unsigned int Dimension2D = 2:
double distanceThreshold = 0.5;
(...)
std::cerr << "Failed for Dimension " << Dimension2D << " and distance threshold " << distanceThreshold << std::endl;
```

2022-11-11 21:03 UTC, jhlegarreta approved these changes
I would still use the declared dimension constants for printing in the messages, and squash both commits into one.

2022-11-12 00:39 UTC, jhlegarreta approved these changes
@PranjalSahu :100:. Thanks.

2022-11-14 03:23 UTC, thewtex approved these changes
:100: :1st_place_medal: well done @PranjalSahu !

2022-11-14 03:23 UTC, merged