BUG: DCMTK reader wrongly rejects file with preamble
InsightSoftwareConsortium/ITK pull request #4110
Opened 2023-07-14 21:19 UTC by pieper

A previous optimization didn't take into account the premable of a dicom file.  This adds a check.

Fixes #4801

2023-07-14 21:21 UTC, pieper commented
@hjmjohnson could you have a look at this?

It fixes https://github.com/InsightSoftwareConsortium/ITK/issues/4108

2023-07-18 08:46 UTC, issakomi commented
I can confirm that DCMTKIO's _CanReadFile_ function returns **false** for valid DICOM files with preamble. I have reproduced it just now.

2023-07-18 15:21 UTC, jhlegarreta commented
Thanks for doing this @pieper. I am willing to give this a :+1: when the following are addressed:
- We're trying to remove/have removed whitespaces before the scope resolution operator, e.g.
https://github.com/InsightSoftwareConsortium/ITK/pull/3664
so please remove them, e.g.
https://github.com/InsightSoftwareConsortium/ITK/pull/4110/files#diff-4f73091b3003136c994a445b6eda56d8ac3e9044936fbb78a0649164a8c31a73R68
- The output stream `<<` insertion operators were removed from `itkExceptionMacro` calls in: https://github.com/InsightSoftwareConsortium/ITK/pull/4057/files, so please remove them:
https://github.com/InsightSoftwareConsortium/ITK/pull/4110/files#diff-4f73091b3003136c994a445b6eda56d8ac3e9044936fbb78a0649164a8c31a73R94
If they should be added back, a separate commit and PR are required.
- Please document the method in the header file:
https://github.com/InsightSoftwareConsortium/ITK/pull/4110/files#diff-4f73091b3003136c994a445b6eda56d8ac3e9044936fbb78a0649164a8c31a73R135
- Adding a test that demonstrates the issue would be required to ensure that we do not run into this issue again.

In general, commits should only fall into one category, `BUG`, `DOC`, `STYLE`, etc. Helps reviewing, keeping changes of different nature separate, keeping a clean history, etc.

2023-07-18 18:01 UTC, pieper commented
Thanks for the review @jhlegarreta - I had tried to add just the one function but it looks like my checkout was against an older target.  I'll fix it.

2024-02-04 13:32 UTC, thewtex requested changes

2024-02-04 13:32 UTC, thewtex commented on Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx
>      }
This could be removed following seek to 0

2024-03-11 02:09 UTC, thewtex commented
#4501 has updates with @jhlegarreta requests addressed (note that `readPreampleDicom` is not in the header, so it is moved to an anonymous namespace instead). Also, replaced the file re-open, close with a seek.

2024-03-14 14:53 UTC, thewtex commented
Superceded by #4501

2024-03-14 14:53 UTC, closed without merging