STYLE: GetGlobalDefaultSplitter replace call_once call with local static
InsightSoftwareConsortium/ITK pull request #4118
Opened 2023-07-17 20:43 UTC by N-Dekker

Replaced a `call_once` call and two global variables with a single local static variable, to simplify the code, while still being thread-safe.

2023-07-18 11:53 UTC, dzenanz approved these changes

2023-07-18 13:04 UTC, blowekamp commented
The ITK Python libraries has some requirements for how global variable should be shared and initialized. I believe @thewtex knows this the best, perhaps get a review from him too?

2023-07-19 13:26 UTC, N-Dekker commented
> The ITK Python libraries has some requirements for how global variable should be shared and initialized. 

Thanks for your comment @blowekamp FYI I did mark the pull request "ready" anyway, because I don't really think the choice between calling `std::call_once` and using thread-safe local static variable initialization would affect Python library requirements. So I just hope the PR passes the review 😃

2023-07-19 13:44 UTC, blowekamp commented
The question I have is not that the new implementation has the same behavior as the old. The questions is if proper behavior for ITK Python should have an implementation for this variable using the custom initialization using the `itkInitGlobalsMacro`.

2023-07-19 15:23 UTC, thewtex requested changes
@blowekamp is right -- this is not providing the required functionality for ITK Python, which is not just magic statics.

2023-07-19 17:26 UTC, thewtex commented
The Singleton functionality, used by ITK Python (although it could also be used in other contexts), uses a lamba; this style change (removing the lambda) is not compatible.

2023-07-19 17:54 UTC, thewtex commented
@N-Dekker I will create a PR to address the global default splitter properly.

2023-07-21 20:32 UTC, thewtex commented
Patch here: https://github.com/InsightSoftwareConsortium/ITK/pull/4122

2023-07-26 13:56 UTC, N-Dekker commented
Closed, as this pull request is superseded by:
- #4122 commit 0f5b4bd3593c3626c017fa1aa3acba0507d81247 by Matt (@thewtex)

2023-07-26 13:56 UTC, closed without merging