PERF: Do not import torch to reduce itk import time
InsightSoftwareConsortium/ITK pull request #4369
Opened 2023-12-14 17:03 UTC by tbaudier

https://discourse.itk.org/t/torch-import-time/6354

Torch takes time to import. In types.py torch is imported to check if it's present or not in the environment, but it's never used.

Now, torch is detected with importlib.metadata.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

2023-12-14 21:46 UTC, thewtex requested changes
@tbaudier thank you for the contribution! :pray: 

Please see a comment inline that could help with the CI failures.

Could also please apply the same method to the other packages in the same file?

2023-12-14 21:46 UTC, thewtex commented on Wrapping/Generators/Python/itk/support/types.py
> +except importlib.metadata.PackageNotFoundError:
Following the CI errors, we may also need `import importlib` at the top.

2023-12-15 13:08 UTC, tbaudier commented
Sorry, I committed the src files but my modified files were in the built folder. Now it's ok.

I tested this code and it worked well:
```py
import torch
import numpy as np
a = np.random.rand(10,10)
t = torch.from_numpy(a)
smoothed = itk.median_image_filter(a, radius=2)
```

According to your advise, I did the modification for xarray too but I did not test it.

For numpy ArrayType, I changed anything because it seems that metadata does not work with submodules

2023-12-16 18:36 UTC, thewtex approved these changes
@tbaudier thank you!

2023-12-16 18:36 UTC, merged