Add inverse capability to KernelTransform
InsightSoftwareConsortium/ITK pull request #4529
Opened 2024-03-19 18:37 UTC by dzenanz

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

2024-03-19 20:16 UTC, thewtex requested changes
Please add a test.

2024-03-20 13:40 UTC, N-Dekker commented on Modules/Core/Transform/include/itkKernelTransform.hxx
> +  typename PointSetType::Pointer targetLandmarks = PointSetType::New();
Please consider using `auto` here. For the return type of `Type::New()` we have agreed that `auto` is appropriate: https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/d1562dd6dbc929ba18fdf8ce8aa86e8337597d7e/SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex#L1558-L1562

2024-03-20 13:44 UTC, N-Dekker commented on Modules/Core/Transform/include/itkKernelTransform.hxx
> +  deepCopyLandmarks(this->GetTargetLandmarks(), targetLandmarks);
Please consider directly copying the internal STL containers of the landmarks:
```cpp

  sourceLandmarks->GetPoints()->CastToSTLContainer() =
    m_SourceLandmarks->GetPoints()->CastToSTLConstContainer();
  targetLandmarks->GetPoints()->CastToSTLContainer() =
    m_TargetLandmarks->GetPoints()->CastToSTLConstContainer();

```

2024-03-20 13:46 UTC, N-Dekker commented on Modules/Core/Transform/include/itkKernelTransform.hxx
> +  typename PointSetType::Pointer targetLandmarks = PointSetType::New();
`const auto` would be even nicer  😇 

```cpp
    const auto sourceLandmarks = PointSetType::New();
    const auto targetLandmarks = PointSetType::New();
```

2024-03-20 13:55 UTC, dzenanz commented
Just as I was making a pull request, I realized that a test is needed. I don't really have time to make a meaningful test (aside from the use in my own program). I also see that https://github.com/InsightSoftwareConsortium/ITK/blob/17a221c0c17dad59755e08c3df618125247334aa/Modules/Core/Transform/test/itkTestTransformGetInverse.cxx#L119 is crashing, probably meaning the inversion method I added is not thread-safe. It would be good if someone took over this PR (I am eying you Niels 😄). Otherwise it is likely going to fester for a long time.

2024-03-20 13:57 UTC, N-Dekker commented on Modules/Core/Transform/include/itkKernelTransform.hxx
> +  inverseTransform->SetStiffness(this->GetStiffness());
I think it's OK for a class to directly access its own data members, without calling Get and Set. So more like:

```cpp
  inverseTransform->m_SourceLandmarks = targetLandmarks;
  inverseTransform->m_TargetLandmarks = sourceLandmarks;
  inverseTransform->m_Stiffness = m_Stiffness;
```

Right?

2024-03-20 14:11 UTC, N-Dekker commented
> It would be good if someone took over this PR

I can ask next week if it may be of interest to elastix. But otherwise this PR does not have a high priority to me. Does it have priority to you? If so, then I think you should try to make it ready, including a simple little test 🤷  Otherwise, just postpone until the summer  🌞 holidays  😸

2024-03-20 14:17 UTC, dzenanz commented
It is not of high priority to me either. So it would be good if you added it to your TODO list for summer holidays 😄

2025-10-08 17:14 UTC, N-Dekker commented
@dzenanz If this feature has no priority, and if writing a test would take too much time, maybe just close it...?

2025-10-08 17:22 UTC, closed without merging

2026-07-21 18:35 UTC, dzenanz commented
Superseded by #6678. Thank you for thoughtful suggestions Niels.