COMP: macOS-11 Azure CI environment EOL
InsightSoftwareConsortium/ITK pull request #4726
Opened 2024-06-17 17:56 UTC by hjmjohnson

The macOS-11 environment is deprecated and scheduled to be removed on June 28th, 2024.

https://learn.microsoft.com/en-us/azure/devops/release-notes/features-timeline-released

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

2024-06-18 17:00 UTC, hjmjohnson commented
@thewtex Would you mind looking this over please?

2024-06-18 22:07 UTC, thewtex requested changes
Please bump to `macos-12` (also Intel) because `macos-14` is ARM and we are already testing it with GitHub Actions.

2024-06-18 22:07 UTC, thewtex commented
Azure Pipelines uses the same images as GitHub Actions:

https://github.com/actions/runner-images

2024-06-19 01:08 UTC, hjmjohnson commented
Changes made.

2024-06-19 03:48 UTC, thewtex approved these changes
@hjmjohnson thanks!

2024-06-19 12:40 UTC, hjmjohnson commented
/azp ITK.macOS.Python

2024-06-19 16:54 UTC, hjmjohnson commented
\azp ITK.macOS.Python

2024-06-19 17:07 UTC, thewtex commented
https://open.cdash.org/viewTest.php?onlyfailed&buildid=9697916

-> One failing, unstable test, `itkLBFGS2Optimizerv4Test`. Perhaps it is worth trying `macos-13` for a compiler update while retaining Intel coverage.

2024-06-19 17:55 UTC, thewtex approved these changes
Thanks, Hans

2024-06-19 19:51 UTC, hjmjohnson commented
@thewtex 

FYI: https://github.com/actions/runner-images?tab=readme-ov-file

macOS-14-large  is intel
macOS-14            is arm


If intel is what we are after, perhaps we just need to use the correct yaml label.

2024-06-19 20:06 UTC, thewtex commented
@hjmjohnson Last time I tried, `macOS-14-large` was not available for free / open source accounts.

2024-06-20 13:00 UTC, merged