BUG: Move InputSpaceName, OutputSpaceName from Transform to Transform…
InsightSoftwareConsortium/ITK pull request #4734
Opened 2024-06-19 20:04 UTC by thewtex

…Base

These were added to support features of the OME-Zarr transform proposals. However, they need to be available in itk::TransformBase instead of itk::Transform for access in TransformIO classes.

2024-06-19 21:17 UTC, PranjalSahu approved these changes
LGTM

2024-06-20 10:33 UTC, N-Dekker commented
Thanks Matt! It looks fine to me, to move those two data members from `itk::Transform<TParametersValueType, VInputDimension, VOutputDimension>` to `itk::TransformBase`. Especially because they don't depend on `VInputDimension` or `VOutputDimension` anyway. 👍 By the way, I would call it an `ENH`, rather than a `BUG`.

Of course I would have liked to see unit tests of the form:

```cpp
    itk::TransformBase & transformBase = ...; // Arrange
    transformBase.SetInputSpaceName(exampleSpaceName); // Act
    EXPECT_EQ(transformBase.GetInputSpaceName(), exampleSpaceName); // Assert
```

Following the AAA pattern: Arrange-Act-Assert. Maybe to consider for a follow-up....?

2024-06-20 10:45 UTC, N-Dekker requested changes
One little request! Please declare those two data members private!  They were originally `private` already!

2024-06-20 10:45 UTC, N-Dekker commented on Modules/Core/Transform/include/itkTransformBase.h
> +  std::string m_OutputSpaceName{};
Please declare them `private`!

2024-06-20 13:58 UTC, blowekamp commented
Any consideration for putting these into the meta-data dictionary over member variables? Would we get serialization for free with any transform IO's if we did that?

2024-06-20 14:08 UTC, N-Dekker commented on Modules/Core/Transform/include/itkTransformBase.h
> +  std::string m_OutputSpaceName{};
@hjmjohnson Why did you mark this as "resolved"?

2024-06-20 14:34 UTC, N-Dekker commented
> Any consideration for putting these into the meta-data dictionary over member variables?

I guess, the question could be, are these "space names" fundamental general properties of any transform, or are they very much application specific? (In the latter case, I guess it would be better to have them as meta-data dictionary entries, rather than member variables.)

Having said so, the decision was made already two years ago, by adding them to `itk::Transform`. So maybe it's best to just leave them as member variables now  🤷

2024-06-20 17:19 UTC, blowekamp commented
> Having said so, the decision was made already almost two years ago, by adding them to `itk::Transform`: pull request #3470 commit [0575485](https://github.com/InsightSoftwareConsortium/ITK/commit/05754850fdeba5971600d3628221cf293c7d4852). So maybe it's best to just leave them as member variables now 🤷

They could still have setter and getter member functions even if they are in the meta-data dictionary. It is more of a question if having them in the dictionary would make serialization easier.

Yes, this question is incidental to the intent of this PR.

2024-06-20 19:13 UTC, thewtex commented
Thanks for the reviews.

@N-Dekker I added the extra coverage requested.

Regarding metadata vs member, I think member is more appropriate in this case: this is an explicit property that we want all tooling / IO to eventually interpret and the explicit interface is helpful. In practice it is easier to work with, including for IO, when the explicit interface is available.

2024-06-20 19:45 UTC, N-Dekker approved these changes
Thanks for addressing my comments, Matt! Approved 👍

2024-06-21 01:40 UTC, merged