BUG: Fix ExposeMetaData<std::vector<double>> im MetaImageIO
InsightSoftwareConsortium/ITK pull request #5064
Opened 2024-12-14 03:48 UTC by issakomi

Indexes were incorrectly accessed with pre-increment instead of post-increment

```cpp
#include <iostream>
#include <vector>

int main()
{
  std::vector<int> v;
  v.push_back(1);
  v.push_back(2);
  v.push_back(3);

  {
    unsigned int i = 0;
    while (i < v.size() - 1)
    {
      std::cout << v[++i] << ' '; // wrong
    }
    std::cout << v[i] << std::endl;
  }

  {
    unsigned int i = 0;
    while (i < v.size() - 1)
    {
      std::cout << v[i++] << ' ';
    }
    std::cout << v[i] << std::endl;
  }

  return 0;
}
```

```
r@deb2:~$ ./a.out 
2 3 3
1 2 3
```

2024-12-14 04:00 UTC, issakomi commented
BTW, `i < v.size() - 1` is a little bit dangerous, what if _size_ is 0. I have tested, segfault. Probably it is unlikely to happen, just FYI.

2024-12-14 04:50 UTC, issakomi commented
BTW, in my code I would prefer something like

```cpp
  {
    const size_t vsize = v.size();
    if (vsize > 0)
    {
        for (size_t i = 0; i < vsize; ++i)
        {
          if (i > 0)
          {
            std::cout << 'x';
          }
          std::cout << v.at(i);
        }
    }
    std::cout << std::endl;
  }
```

Otherwise there can be issues if vector size is 0 or 1. Maybe there is something is _std_ from C++42 for the purpose?

2024-12-14 12:01 UTC, hjmjohnson requested changes
I think this can be further improved using a for loop for clarity

2024-12-14 12:01 UTC, hjmjohnson commented on Modules/IO/Meta/src/itkMetaImageIO.cxx
> +        strs << vval[i++] << ' ';
I prefer a function call like:
```c++
// Function to join strings with a delimiter similar to python's   ' '.join([1, 2, 3 ])
void join(const std::vector<std::string>& elements, const std::string& delimiter,  std::ostringstream strs) {
    for (size_t i = 0; i < elements.size(); ++i) {
        strs << elements[i];
        if (i != elements.size() - 1) {
            strs << delimiter;
        }
    }
}
```

This avoids the pre-post increment relationship to the [] operator.

2024-12-14 12:30 UTC, dzenanz approved these changes
Good as-is. It can be further refactored in a follow-up commit or PR.

2024-12-14 16:26 UTC, hjmjohnson approved these changes
Agree @dzenanz  Thanks for the insight.

2024-12-14 16:26 UTC, merged

2024-12-16 16:09 UTC, issakomi commented
@thewtex  Maybe this commit could be included in upcoming 5.4 bugfix release?

2024-12-16 16:12 UTC, blowekamp commented
> @thewtex Maybe this commit could be included in the upcoming 5.4 bugfix release?

+1